version: "2"
services:
  app:
    build:
      args:
        user: user1
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: projeto-app
    container_name: projeto-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - projeto

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: 12345
    networks:
      - projeto

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "8011:80"
    depends_on:
      - db
    networks:
      - projeto

  nginx:
    image: nginx:1.17-alpine
    container_name: projeto-nginx
    restart: unless-stopped
    ports:
      - 8010:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - projeto

networks:
  projeto:
    driver: bridge
